### ISSUE TITLE
More flexible index pattern

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/logsearch-smoke-tests#1]
These tests assume that indices are namespaced by org and space. This may not always be the case--actually, @cnelson has found that that index strategy results in unusably bad performance on our cluster. These tests should expose a more flexible method to configure search index. One option might be go templates:

```json
{
  "elasticsearch_app_index": "logs-app-{{org}}-{{date}}"
}
```

If that makes sense, I'd be happy to send a patch.

**Comment by Infra-Red** [comment]
It's definitely make sense, will be happy to have this improvements merged.

--
Regards,
Andrei

24 апр. 2017 г., 23:15 +0300, Joshua Carp <notifications@github.com>, писал:
